name: Convert SVG to PNG

on:
  workflow_dispatch:
    inputs:
      DRAFTBRANCH:
        description: 'Branch with the file to convert (should not be main)'
        required: true
      ORIGINAL:
        description: 'File to convert WITH path but NO extension'
        required: true

jobs:
  convert:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.DRAFTBRANCH }}
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Convert
      run: |
        npm install svg2png -g
        svg2png ${{ github.event.inputs.ORIGINAL }}.svg --output=${{ github.event.inputs.ORIGINAL }}.png --width=1280 --height=672
    
    - name: Commit and push 
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'commit png of report header image'
        add: '*.png'
 
